spring.application.name: Movilizer Connector

# Profiles
#spring.profiles: local, demo, preprod, prod

# Active profile should be overwritten by application.properties or an argument: gradle :bootRun -Pspring.profiles.active=dev
spring.profiles.active: local

# Movilizer config
movilizer:
  env: demo
  protocol: v14
  polling-rate: 10000 #millis
  max-items: 10000 #datacontainers/replies in the webservice response
  charset: UTF-8
  auth:
    systemId: 51840015
    password: 1337
  masterdata:
    init: false
    default-group: ALL
  movelets:
    init: false
    version: 1
  participants:
    init: false
    suffix: "@movilizer.com"
  datacontainer:
    log: true
    dir: logs/datacontainers/${movilizer.env}

# Logging config
logging:
  level.: INFO
  file: logs/movilizer-connector-info.log

#Tomcat config
server:
  contextPath: /movilizer-${spring.profiles.active}
  port: 8080

# Actuator management config
management:
  address: 127.0.0.1
  port: 8081
