spring.application.name: Movilizer Connector - local

# Movilizer config
movilizer:
  env: demo
  polling-rate: 10000 #millis
  auth:
    systemId: 1234
    password: pass

# Logging config
logging:
  level.: INFO
  file: logs/movilizer-connector-info.log

#Tomcat config
server:
  contextPath: /movilizer-local
  port: 8080

# Actuator management config
management:
  address: 127.0.0.1
  port: 8081